"""added timestamps to keep track of number of request in time window

Revision ID: 0c681bbdf26d
Revises: 00cc634fecc3
Create Date: 2026-05-29 20:07:51.977282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c681bbdf26d'
down_revision: Union[str, Sequence[str], None] = '00cc634fecc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratecount', sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratecount', 'last_reset_at')
    # ### end Alembic commands ###
