"""removed ratecount model, schema, and views

Revision ID: 51f8a2253d51
Revises: 9ffd074ad231
Create Date: 2026-05-30 23:45:18.219935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51f8a2253d51'
down_revision: Union[str, Sequence[str], None] = '9ffd074ad231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratecount_id'), table_name='ratecount')
    op.drop_table('ratecount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratecount',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_reset_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ratecount_pkey'))
    )
    op.create_index(op.f('ix_ratecount_id'), 'ratecount', ['id'], unique=False)
    # ### end Alembic commands ###
