"""removed rate counters

Revision ID: 65c20e964686
Revises: 628d1087fc4a
Create Date: 2026-05-25 13:53:07.383933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c20e964686'
down_revision: Union[str, Sequence[str], None] = '628d1087fc4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rate_limit')
    op.drop_column('users', 'counter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('counter', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('rate_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
